# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_count', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Knots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_size', models.TextField(blank=True, null=True)),
                ('small', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('has_active_contract', models.BooleanField(default=False)),
                ('point_id', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('slogan', models.CharField(blank=True, max_length=500, null=True)),
                ('slugged_title', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('tel_1', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('uuid', models.CharField(blank=True, max_length=200, null=True)),
                ('guilds', models.ManyToManyField(to='ibartar.Guilds')),
                ('knots', models.ManyToManyField(to='ibartar.Knots')),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ibartar.Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('credibility', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('reliability', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='points',
            name='rates',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ibartar.Rates'),
        ),
    ]
