# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibartar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibartar.Logo'),
        ),
        migrations.AlterField(
            model_name='points',
            name='rates',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibartar.Rates'),
        ),
    ]
